const mockData = {
  currentUser: {
    id: 1,
    name: 'Holland',
    role: 'Admin',
    email: 'admin@talentbank.com',
  },
  dashboard: {
    overviewCards: [
      { title: 'Total Projects', value: 20, note: 'Delivery pipeline', theme: 'coral' },
      { title: 'Team Members', value: 20, note: 'Across all units', theme: 'sun' },
      { title: 'Active Employees', value: 20, note: 'Currently active', theme: 'violet' },
      { title: 'Resolved Tickets', value: 20, note: 'Closed by support', theme: 'mint' },
      { title: 'Pending Reviews', value: 20, note: 'Projects under review', theme: 'peach' },
      { title: 'Open Tickets', value: 20, note: 'Need follow-up', theme: 'sky' },
    ],
    leadStats: [
      { label: 'Assigned', value: 8, percent: 25, color: '#f4c84a' },
      { label: 'In progress', value: 1, percent: 15, color: '#6e5a8e' },
      { label: 'Review', value: 1, percent: 25, color: '#5da16f' },
      { label: 'Final', value: 2, percent: 35, color: '#ee6257' },
    ],
    salesTrend: [
      { day: 'Mon', total: 3, converted: 1 },
      { day: 'Tue', total: 8, converted: 1 },
      { day: 'Wed', total: 6, converted: 4 },
      { day: 'Thu', total: 10, converted: 5 },
      { day: 'Fri', total: 8, converted: 1 },
      { day: 'Sat', total: 8, converted: 7 },
      { day: 'Sun', total: 4, converted: 3 },
    ],
    supportSummary: [
      { label: 'Solved', value: 18, color: '#eb5c57' },
      { label: 'Unsolved', value: 8, color: '#f3cb4d' },
      { label: 'In progress', value: 26, color: '#63a26f' },
    ],
  },
  users: [
    {
      id: '01',
      employeeId: 'TAL001',
      name: 'Tom Holland',
      mobile: '9876543210',
      email: 'tomholland@gmail.com',
      role: 'Executive manager',
      status: 'Active',
      joinedOn: '03.06.2025',
    },
    {
      id: '02',
      employeeId: 'TAL002',
      name: 'Tom Hiddleston',
      mobile: '9123456780',
      email: 'tom.h@talentbank.com',
      role: 'Sales manager',
      status: 'Active',
      joinedOn: '05.06.2025',
    },
    {
      id: '03',
      employeeId: 'TAL003',
      name: 'Zendaya Coleman',
      mobile: '9000154321',
      email: 'zendaya@talentbank.com',
      role: 'Sales manager',
      status: 'Resign',
      joinedOn: '08.06.2025',
    },
    {
      id: '04',
      employeeId: 'TAL004',
      name: 'Jacob Batalon',
      mobile: '9345678123',
      email: 'jacob@talentbank.com',
      role: 'Sales manager',
      status: 'Active',
      joinedOn: '10.06.2025',
    },
    {
      id: '05',
      employeeId: 'TAL005',
      name: 'Benedict Wong',
      mobile: '9234567812',
      email: 'benedict@talentbank.com',
      role: 'General manager',
      status: 'Inactive',
      joinedOn: '13.06.2025',
    },
  ],
  projects: [
    {
      code: 'PRJ-001',
      name: 'Core Banking Revamp',
      owner: 'Holland',
      progress: 72,
      priority: 'High',
      status: 'In progress',
      dueDate: '24 Apr 2026',
    },
    {
      code: 'PRJ-002',
      name: 'Loan Onboarding Flow',
      owner: 'Zendaya',
      progress: 54,
      priority: 'Medium',
      status: 'Review',
      dueDate: '28 Apr 2026',
    },
    {
      code: 'PRJ-003',
      name: 'Recruitment Dashboard',
      owner: 'Tom Holland',
      progress: 88,
      priority: 'High',
      status: 'Final',
      dueDate: '03 May 2026',
    },
    {
      code: 'PRJ-004',
      name: 'Support Automation',
      owner: 'Jacob',
      progress: 39,
      priority: 'Low',
      status: 'Assigned',
      dueDate: '07 May 2026',
    },
  ],
  tickets: [
    {
      id: 'TIC-101',
      subject: 'Unable to approve user leaves',
      requester: 'Sarah M',
      team: 'HR',
      priority: 'High',
      status: 'Solved',
      updatedAt: '17 Apr 2026, 2:30 PM',
    },
    {
      id: 'TIC-102',
      subject: 'Sales report export failing',
      requester: 'Ron C',
      team: 'Sales',
      priority: 'Medium',
      status: 'In progress',
      updatedAt: '17 Apr 2026, 1:05 PM',
    },
    {
      id: 'TIC-103',
      subject: 'Need project role access',
      requester: 'Julie A',
      team: 'Operations',
      priority: 'Low',
      status: 'Unsolved',
      updatedAt: '17 Apr 2026, 11:18 AM',
    },
    {
      id: 'TIC-104',
      subject: 'Dashboard widget mismatch',
      requester: 'Megan P',
      team: 'Management',
      priority: 'High',
      status: 'Solved',
      updatedAt: '16 Apr 2026, 5:42 PM',
    },
  ],
};

module.exports = {
  mockData,
};
